export default APP_SCREEN = Object.freeze({
  UN_AUTHORIZE: 'Un Authorize',
  AUTHORIZE: 'Authorize',
  HOME_STACK: 'Home Stack',
  MESSAGE_STACK: 'Message Stack',
  CALENDAR_STACK: 'Calendar Stack',
  PROFILE_STACK: 'Profile Stack',
  LOGIN: 'Login',
  SIGN_UP: 'Sign Up',
  HOME: 'Home',
  MAKE_APPOINTMENT: 'Make Appointment',
  APPOINTMENTS: 'Appointments',
  APPOINTMENT_CHECKOUT: 'Appointment Checkout',
  COURSES: 'Course List',
  COURSE_DETAILS: 'Course Details',
});
