export default doctorInfo = [
  {
    id: '1',
    name: 'Trần Minh Khuyên',
    speciality: 'Tâm lý học trị liệu',
    rating: 4.7,
    location: 'Quận 5',
    briefInfo:
      'Sức khoẻ tâm thần cần được coi trọng ngang với sức khoẻ thể chất. Bệnh tâm thần có thể chữa khỏi nếu phát hiện sớm và điều trị kịp thời.',
    avatar: 'https://i.imgur.com/VBAbTiO.png',
  },
  {
    id: '2',
    name: 'Huỳnh Thanh Hiển',
    speciality: 'Tâm lý học tâm thần',
    rating: 4.7,
    location: 'Quận 7',
    briefInfo: 'I dont give a sh*t about patients',
    avatar: 'https://i.imgur.com/eAliZCk.png',
  },
  {
    id: '3',
    name: 'Nguyễn Thị Yến Chi',
    speciality: 'Báo nhà',
    rating: 3.0,
    location: 'Biên hòa',
    briefInfo: 'I dont give a sh*t about patients',
    avatar: 'https://i.imgur.com/Y95k02M.png',
  },
  {
    id: '4',
    name: 'Hoàng Ngọc Trâm',
    speciality: 'Tâm lý học tâm thần',
    rating: 4.5,
    location: 'Quận 3',
    briefInfo: 'I dont give a sh*t about patients',
    avatar: 'https://i.imgur.com/QUWhdnh.png',
  },
  {
    id: '5',
    name: 'Lê Nguyễn Thụy Phương',
    speciality: 'Tâm lý học lâm sàng',
    rating: 4.2,
    location: 'Quận 1',
    briefInfo: 'I dont give a sh*t about patients',
    avatar: 'https://i.imgur.com/R2lDac4.png',
  },
  {
    id: '6',
    name: 'Sunny Đặng Phương',
    speciality: 'Tâm lý học lâm sàng',
    rating: 4.5,
    location: 'Quận 1',
    briefInfo: 'I dont give a sh*t about patients',
    avatar: 'https://i.imgur.com/r5EB6Fm.png',
  },
];
