export const icons = {
  send: require('./source/send.png'),
  back: require('./source/arrow-left-new.png'),
  bell: require('./source/bell.png'),
  bullet: require('./source/bullet.png'),
  close: require('./source/ic_close.png'),
  plus: require('./source/ic_plus.png'),
  home: require('./source/ic_home.png'),
  homeFilled: require('./source/ic_home.png'),
  heart: require('./source/ic_heart.png'),
  search: require('./source/ic_search.png'),
  user: require('./source/ic_user.png'),
  arrow_down: require('./source/arrow_down.png'),
  check: require('./source/check.png'),
  eye: require('./source/eye.png'),
  eyeClose: require('./source/eye-close.png'),
  star: require('./source/star.png'),
  location: require('./source/location.png'),
  calendar: require('./source/calendar.png'),
  editSquare: require('./source/edit-square.png'),
  dot: require('./source/dot.png'),
  chat: require('./source/chat.png'),
};

export type IconTypes = keyof typeof icons;
